language: r
sudo: false
cache: packages

r_packages:
  - covr
r_github_packages:
  - leeper/csvy
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX=g++-4.9
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

after_success:
  - Rscript -e 'library("covr");codecov()'
